In [2]:
import pandas as pd
import os
import fnmatch

In [3]:
##read base file.
Base_df=pd.read_csv('/home/jovyan/Property_proj/Data/2016_GCP_SSC_for_NSW_short-header/2016_Census_NSW_suburbs/2016Census_G02_NSW_SSC.csv')
##read data file
df=pd.read_csv('/home/jovyan/Property_proj/Data/2016_GCP_SSC_for_NSW_short-header/2016_Census_NSW_suburbs/2016Census_G53A_NSW_SSC.csv')
##read meta data(suburb code to name mapping)
df_ref_data = pd.read_excel('/home/jovyan/Property_proj/Data/2016_GCP_SSC_for_NSW_short-header/Metadata/2016Census_geog_desc_1st_and_2nd_release.xlsx', index_col=None,
                  sheetname ='2016_ASGS_Non-ABS_Structures')

/opt/conda/lib/python3.6/site-packages/pandas/io/excel.py:329: FutureWarning: The `sheetname` keyword is deprecated, use `sheet_name` instead
  **kwds)

In [43]:
commute_df=pd.read_csv('/home/jovyan/Property_proj/Data/2016_GCP_SSC_for_NSW_short-header/2016_Census_NSW_suburbs/2016Census_G59_NSW_SSC.csv')

In [19]:
#commute_df.set_index('SSC_CODE_2016')

In [37]:
#commute_df.loc[:, ('SSC_CODE_2016',commute_df.columns.to_series().str.endswith("_P"))]

In [42]:
commute_df1=commute_df.filter(regex='_P')
a=commute_df1.columns.values

array(['One_method_Train_P', 'One_method_Bus_P', 'One_method_Ferry_P',
       'One_met_Tram_incl_lt_rail_P', 'One_method_Taxi_P',
       'One_method_Car_as_driver_P', 'One_method_Car_as_passenger_P',
       'One_method_Truck_P', 'One_method_Motorbike_scootr_P',
       'One_method_Bicycle_P', 'One_method_Other_P',
       'One_method_Walked_only_P', 'One_method_Tot_one_method_P',
       'Two_methods_Train_Bus_P', 'Two_methods_Train_Ferry_P',
       'Two_mt_trn_Trm_incl_lt_rl_P', 'Two_methods_Trn_Car_as_drvr_P',
       'Two_methods_Trn_Car_as_pass_P', 'Two_methods_Train_Other_P',
       'Two_methods_Train_Tot_P', 'Two_methods_Bus_Ferry_P',
       'Two_mth_Bu_Trm_inc_lt_rl_P', 'Two_methods_Bus_Car_as_drvr_P',
       'Two_methods_Bus_Car_as_pass_P', 'Two_methods_Bus_Other_P',
       'Two_methods_Bus_Tot_P', 'Two_methds_Othr_two_methds_P',
       'Two_methods_Tot_two_methods_P', 'Three_meth_Trn_two_othr_met_P',
       'Three_met_Bs_2_ot_met_ex_tr_P', 'Three_meth_Othr_three_meth_P',
       'Three_meth_Tot_three_meth_P', 'Worked_home_P',
       'Did_not_go_to_work_P', 'Method_travel_to_work_ns_P', 'Tot_P'], dtype=object)

In [47]:
commute_df3=commute_df.loc[:, a)]

TypeError: unhashable type: 'numpy.ndarray'

In [45]:
commute_df3

,One_method_Train_P,One_method_Bus_P,One_method_Ferry_P,One_met_Tram_incl_lt_rail_P,One_method_Taxi_P,One_method_Car_as_driver_P,One_method_Car_as_passenger_P,One_method_Truck_P,One_method_Motorbike_scootr_P,One_method_Bicycle_P,...,Two_methds_Othr_two_methds_P,Two_methods_Tot_two_methods_P,Three_meth_Trn_two_othr_met_P,Three_met_Bs_2_ot_met_ex_tr_P,Three_meth_Othr_three_meth_P,Three_meth_Tot_three_meth_P,Worked_home_P,Did_not_go_to_work_P,Method_travel_to_work_ns_P,Tot_P
0,0,0,0,0,0,7,0,0,0,0,...,0,0,0,0,0,0,4,3,0,13
1,70,40,0,0,0,1618,120,44,7,3,...,21,117,19,0,0,20,68,154,25,2297
2,9,335,139,3,0,1475,85,11,18,27,...,15,101,13,3,0,14,153,216,10,2660
3,0,0,0,0,0,435,29,0,6,3,...,8,8,0,0,0,3,23,54,3,573
4,0,0,0,0,0,5,0,0,0,0,...,0,0,0,0,0,0,3,0,0,14
5,0,3,0,0,3,676,43,10,0,3,...,8,12,0,0,0,0,25,136,11,943
6,0,3,0,0,0,642,46,10,3,0,...,4,4,0,0,0,0,33,124,7,906
7,0,0,0,0,0,22,0,0,0,0,...,0,0,0,0,0,0,18,0,0,61
8,12,11,0,0,0,2019,147,21,5,3,...,21,29,7,0,0,9,83,328,20,2695
9,3,3,0,0,0,699,52,12,4,0,...,12,13,0,0,0,0,20,117,15,962
10,0,0,0,0,0,92,3,0,0,0,...,0,0,0,0,0,0,0,16,0,121
11,0,0,0,0,0,3,0,0,0,0,...,0,0,0,0,0,0,3,0,0,5
12,0,0,0,0,0,11,0,0,0,0,...,0,0,0,0,0,0,3,3,0,16
13,120,115,0,0,5,1333,73,13,8,0,...,13,163,18,0,0,22,43,135,21,2074
14,0,0,0,0,0,74,7,0,0,0,...,0,3,0,0,0,0,9,9,0,136
15,18,79,0,0,5,2166,142,12,26,52,...,21,41,0,4,0,3,76,351,35,3107
16,24,37,0,0,0,1772,112,15,19,33,...,12,26,0,0,0,0,126,263,22,2521
17,0,0,0,0,0,288,11,9,0,0,...,0,0,0,0,0,0,11,43,4,376
18,0,0,0,0,0,22,0,3,0,0,...,0,0,0,0,0,0,5,3,0,42
19,0,0,0,0,0,11,0,0,0,0,...,0,0,0,0,0,0,4,0,0,21
20,8,0,0,0,0,318,15,16,0,0,...,0,14,0,0,0,0,27,34,0,463
21,16,29,0,0,0,279,46,4,10,0,...,0,38,3,0,0,3,8,47,25,525
22,0,0,0,0,0,25,0,0,0,0,...,0,0,0,0,0,0,0,3,0,30
23,0,0,0,0,0,17,0,0,0,0,...,0,0,0,0,0,0,12,5,0,34
24,54,30,0,0,5,4789,296,65,20,9,...,34,102,5,3,0,7,154,684,41,6347
25,62,18,0,0,0,2116,149,37,14,13,...,22,40,3,0,0,8,72,306,25,2906
26,3,6,0,0,9,1502,88,5,5,38,...,22,22,3,0,0,6,119,228,3,2288
27,0,5,0,0,0,229,11,9,0,0,...,0,0,0,0,0,0,8,35,0,311
28,0,0,0,0,0,39,0,3,0,0,...,0,0,0,0,0,0,22,11,0,82
29,1528,288,0,3,33,1614,146,20,96,260,...,33,449,37,0,3,40,220,364,34,5670
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4496,0,0,0,0,0,48,9,0,0,0,...,0,0,0,0,0,0,15,3,3,86
4497,0,0,0,0,0,11,0,0,0,0,...,0,0,0,0,0,0,12,0,0,29
4498,0,0,0,0,0,34,0,0,0,0,...,0,0,0,0,0,0,6,5,0,42
4499,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,3,0,0,7
4500,0,0,0,0,0,12,0,0,0,0,...,0,0,0,0,0,0,0,0,0,17
4501,17,4,0,0,0,389,24,17,0,4,...,11,25,0,0,0,3,30,53,4,577
4502,0,0,0,0,0,80,3,9,0,0,...,0,0,0,0,0,0,11,5,0,104
4503,0,0,0,0,0,535,39,8,0,0,...,3,3,0,0,0,0,47,61,12,738
4504,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4505,59,0,0,0,0,231,33,5,0,0,...,3,16,0,0,0,0,17,19,5,404
4506,0,0,0,0,0,69,11,3,0,0,...,0,0,0,0,0,0,17,21,5,151
4507,0,0,0,0,0,59,3,4,0,0,...,0,0,0,0,0,0,21,15,0,121
4508,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4509,19,5,0,0,0,406,26,16,0,0,...,4,15,0,0,0,0,22,52,3,570
4510,0,0,0,0,0,8,0,0,0,0,...,0,0,0,0,0,0,3,0,0,11
4511,0,0,0,0,0,30,0,0,0,0,...,0,0,0,0,0,0,5,5,0,43
4512,0,0,0,0,0,71,3,4,0,0,...,0,0,0,0,0,0,11,14,0,109
4513,0,0,0,0,0,36,0,0,0,0,...,0,0,0,0,0,0,22,11,3,80
4514,0,0,0,0,3,55,6,0,0,0,...,0,0,0,0,0,0,3,9,3,87
4515,0,0,0,0,0,460,34,6,0,5,...,0,3,0,0,0,0,40,41,3,621
4516,0,0,0,0,0,122,8,4,0,0,...,3,3,0,0,0,0,21,11,5,179
4517,3,3,0,0,10,2806,235,73,11,7,...,26,26,0,0,0,0,183,430,51,4033
4518,147,0,0,0,6,987,54,5,0,8,...,11,50,3,0,0,3,112,160,9,1566
4519,0,0,0,0,0,25,0,0,0,0,...,0,0,0,0,0,0,3,12,0,46
4520,0,0,0,0,0,5,0,0,0,0,...,0,0,0,0,0,0,0,0,0,8
4521,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4522,0,0,0,0,0,19,0,0,0,0,...,0,0,0,0,0,0,4,3,4,30
4523,892,850,0,0,31,1712,198,12,89,130,...,36,319,36,4,0,46,170,335,37,5186
4524,272,174,8,5,12,1355,221,36,21,39,...,21,158,24,0,0,25,112,360,74,3331
4525,4,0,0,0,0,24,0,0,0,0,...,0,0,0,0,0,0,0,79,7,130